### PR TITLE
add pdbfixer to environment file

### LINKED ISSUE #17: include pdbfixer in environment
Day3 Practical 1 https://github.com/MDAnalysis/WorkshopPrace2021/blob/main/Day3-Session2-Practical/creating_and_manipulating_universes.ipynb requires *pdbfixer* which is not included in the environment file.

```
conda install pdbfixer
```

### PR DESCRIPTION
**Pull request by orbeckst**
close #17

### CODE REVIEW

**Comment by orbeckst** [comment]
@mnmelo I assume you installed pdbfixer on Lisa, too?

**Comment by IAlibay** [comment]
> @mnmelo I assume you installed pdbfixer on Lisa, too?

Going by discord discussions it seems like it.

**Comment by mnmelo** [comment]
Indeed!
Because the conda install had to be done as a submission job I have the set of commands I actually run as a semi-neat SLURM job. Would that make sense to bring into this repo?

**Comment by orbeckst** [comment]
In my opinion, this repo will be the primary permanent record so _anything_ that will help us in the future should go here. Just put it into an appropriately directory ("development" or "DO_NOT_TOUCH_EVER_YES_I_MEAN_YOU")

**Comment by mnmelo** [comment]
On this topic, is there a nice way to specify which `jupyter nbextensions` to activate for the environment? So far we got 8.

**Comment by IAlibay** [comment]
@mnmelo I don't think you can do it directly from a yaml file, but we can/should do this: https://github.com/IAlibay/MDAnalysis-talks/tree/main/binder

That way we can just set up binder to run on top of the repo.

**Pull request merged**
